### ISSUE TITLE
How can I use it in python?

### ISSUE THREAD

**Issue by motom001** [LeMaker/WiringBP#4]
I installed wiringBP but how can I use it in python? (using bananian)

```
root@bananapipro / # python
Python 2.7.3 (default, Mar 14 2014, 17:55:54)
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import wiringBP
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named wiringBP
>>> import wiringPi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named wiringPi
>>> import wiringbp2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named wiringbp2
>>> import wiringpi2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named wiringpi2
>>>
```

**Comment by Tony-HIT** [comment]
I do not try use the wringPi under Python, but as I see the wiringPi2 for raspberry pi python just import something from wiringPi, so I think you can refer to the same method to make it work.

**Comment by motom001** [comment]
doesn't work:

```
>>> import wiringPi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named wiringPi
```

**Comment by Tony-HIT** [comment]
Do we not need to pack the wirngPi into python library, just use import?
